#!/bin/sh
steamPath="$HOME/.local/share/Steam/steamapps"
manifestFiles=$(ls $steamPath/*.acf)
dbPath="$HOME/.config/dsteam/db"

mkdir -p $HOME/.config/dsteam
[ -f $dbPath ] && rm $dbPath

echo "Scanning app manifests..."
for i in $manifestFiles
do
	appID=$(awk '/appid/ { gsub("\"", ""); print $2}' $i)
	name=$(awk -F'\t' '/name/ { gsub("\"", ""); print $4}' $i)

	# Check if this application is a proton version, or some other steam related program.
	# You can't really launch those by themselves
	case $name in
		Proton*) continue ;;
		"Steam Linux Runtime"*) continue ;;
		Steamworks*) continue ;;
	esac

	echo "$name"
	echo "$name;$appID" >> $dbPath
done
