#!/bin/sh
steamPath="$HOME/.local/share/Steam/steamapps"
libraryfolders="$HOME/.steam/steam/config/libraryfolders.vdf"
libraryPaths=$(awk -F'\t' '/path/ { gsub("\"", ""); print $5 }' < $libraryfolders)
dbPath="$HOME/.config/dsteam/db"

for i in $libraryPaths
do
	manifestFiles="$manifestFiles $(ls $i/steamapps/*.acf 2>/dev/null)"
done

mkdir -p $HOME/.config/dsteam
[ -f $dbPath ] && rm $dbPath

echo "Scanning app manifests..."
for i in $manifestFiles
do
	appID=$(awk '/"appid"/ { gsub("\"", ""); print $2}' $i)
	name=$(awk -F'\t' '/"name"/ { gsub("\"", ""); print $4}' $i)

	# Check if this application is a proton version, or some other steam related program.
	# You can't really launch those by themselves
	case $name in
		Proton*) continue ;;
		"Steam Linux Runtime"*) continue ;;
		Steamworks*) continue ;;
	esac

	# Empty name
	[ -z "$name" ] && continue

	# Empty ID
	[ -z "$appID" ] && continue

	echo "$name - $appID"
	echo "$name;$appID" >> $dbPath
done
